[workspace]
members = ["tvm-engine", "tvm-engine-types", "tvm-engine-precompiles"]

[workspace.package]
version = "0.1.0-alpha"
edition = "2021"
authors = ["Charles.liu"]
description = "Virtual Machine Engine for TOP-Chain"
rust-version = "1.66"

[workspace.dependencies]
