// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf_types/pbasic.proto

#ifndef PROTOBUF_INCLUDED_protobuf_5ftypes_2fpbasic_2eproto
#define PROTOBUF_INCLUDED_protobuf_5ftypes_2fpbasic_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_protobuf_5ftypes_2fpbasic_2eproto 

namespace protobuf_protobuf_5ftypes_2fpbasic_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_protobuf_5ftypes_2fpbasic_2eproto
namespace top {
namespace tvm_engine {
namespace basic {
class PAddress;
class PAddressDefaultTypeInternal;
extern PAddressDefaultTypeInternal _PAddress_default_instance_;
}  // namespace basic
}  // namespace tvm_engine
}  // namespace top
namespace google {
namespace protobuf {
template<> ::top::tvm_engine::basic::PAddress* Arena::CreateMaybeMessage<::top::tvm_engine::basic::PAddress>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace top {
namespace tvm_engine {
namespace basic {

// ===================================================================

class PAddress : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:top.tvm_engine.basic.PAddress) */ {
 public:
  PAddress();
  virtual ~PAddress();

  PAddress(const PAddress& from);

  inline PAddress& operator=(const PAddress& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PAddress(PAddress&& from) noexcept
    : PAddress() {
    *this = ::std::move(from);
  }

  inline PAddress& operator=(PAddress&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PAddress& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PAddress* internal_default_instance() {
    return reinterpret_cast<const PAddress*>(
               &_PAddress_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(PAddress* other);
  friend void swap(PAddress& a, PAddress& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PAddress* New() const final {
    return CreateMaybeMessage<PAddress>(NULL);
  }

  PAddress* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PAddress>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PAddress& from);
  void MergeFrom(const PAddress& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PAddress* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes value = 1;
  void clear_value();
  static const int kValueFieldNumber = 1;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  #if LANG_CXX11
  void set_value(::std::string&& value);
  #endif
  void set_value(const char* value);
  void set_value(const void* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // @@protoc_insertion_point(class_scope:top.tvm_engine.basic.PAddress)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_protobuf_5ftypes_2fpbasic_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PAddress

// bytes value = 1;
inline void PAddress::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PAddress::value() const {
  // @@protoc_insertion_point(field_get:top.tvm_engine.basic.PAddress.value)
  return value_.GetNoArena();
}
inline void PAddress::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:top.tvm_engine.basic.PAddress.value)
}
#if LANG_CXX11
inline void PAddress::set_value(::std::string&& value) {
  
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:top.tvm_engine.basic.PAddress.value)
}
#endif
inline void PAddress::set_value(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:top.tvm_engine.basic.PAddress.value)
}
inline void PAddress::set_value(const void* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:top.tvm_engine.basic.PAddress.value)
}
inline ::std::string* PAddress::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:top.tvm_engine.basic.PAddress.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PAddress::release_value() {
  // @@protoc_insertion_point(field_release:top.tvm_engine.basic.PAddress.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PAddress::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:top.tvm_engine.basic.PAddress.value)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace basic
}  // namespace tvm_engine
}  // namespace top

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_protobuf_5ftypes_2fpbasic_2eproto
