// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf_types/pparameters.proto

#include "protobuf_types/pparameters.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_protobuf_5ftypes_2fpbasic_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_protobuf_5ftypes_2fpbasic_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_PAddress;
}  // namespace protobuf_protobuf_5ftypes_2fpbasic_2eproto
namespace protobuf_protobuf_5ftypes_2fpparameters_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_protobuf_5ftypes_2fpparameters_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_PReturnResult_PU256;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_protobuf_5ftypes_2fpparameters_2eproto ::google::protobuf::internal::SCCInfo<2> scc_info_PReturnResult_PLog;
}  // namespace protobuf_protobuf_5ftypes_2fpparameters_2eproto
namespace top {
namespace tvm_engine {
namespace parameters {
class PReturnResult_PU256DefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PReturnResult_PU256>
      _instance;
} _PReturnResult_PU256_default_instance_;
class PReturnResult_PLogDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PReturnResult_PLog>
      _instance;
} _PReturnResult_PLog_default_instance_;
class PReturnResultDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PReturnResult>
      _instance;
} _PReturnResult_default_instance_;
class PCallArgsDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PCallArgs>
      _instance;
} _PCallArgs_default_instance_;
}  // namespace parameters
}  // namespace tvm_engine
}  // namespace top
namespace protobuf_protobuf_5ftypes_2fpparameters_2eproto {
static void InitDefaultsPReturnResult_PU256() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::top::tvm_engine::parameters::_PReturnResult_PU256_default_instance_;
    new (ptr) ::top::tvm_engine::parameters::PReturnResult_PU256();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::top::tvm_engine::parameters::PReturnResult_PU256::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_PReturnResult_PU256 =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsPReturnResult_PU256}, {}};

static void InitDefaultsPReturnResult_PLog() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::top::tvm_engine::parameters::_PReturnResult_PLog_default_instance_;
    new (ptr) ::top::tvm_engine::parameters::PReturnResult_PLog();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::top::tvm_engine::parameters::PReturnResult_PLog::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_PReturnResult_PLog =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsPReturnResult_PLog}, {
      &protobuf_protobuf_5ftypes_2fpbasic_2eproto::scc_info_PAddress.base,
      &protobuf_protobuf_5ftypes_2fpparameters_2eproto::scc_info_PReturnResult_PU256.base,}};

static void InitDefaultsPReturnResult() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::top::tvm_engine::parameters::_PReturnResult_default_instance_;
    new (ptr) ::top::tvm_engine::parameters::PReturnResult();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::top::tvm_engine::parameters::PReturnResult::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_PReturnResult =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsPReturnResult}, {
      &protobuf_protobuf_5ftypes_2fpparameters_2eproto::scc_info_PReturnResult_PLog.base,}};

static void InitDefaultsPCallArgs() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::top::tvm_engine::parameters::_PCallArgs_default_instance_;
    new (ptr) ::top::tvm_engine::parameters::PCallArgs();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::top::tvm_engine::parameters::PCallArgs::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_PCallArgs =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsPCallArgs}, {
      &protobuf_protobuf_5ftypes_2fpbasic_2eproto::scc_info_PAddress.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_PReturnResult_PU256.base);
  ::google::protobuf::internal::InitSCC(&scc_info_PReturnResult_PLog.base);
  ::google::protobuf::internal::InitSCC(&scc_info_PReturnResult.base);
  ::google::protobuf::internal::InitSCC(&scc_info_PCallArgs.base);
}

::google::protobuf::Metadata file_level_metadata[4];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::top::tvm_engine::parameters::PReturnResult_PU256, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::top::tvm_engine::parameters::PReturnResult_PU256, data_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::top::tvm_engine::parameters::PReturnResult_PLog, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::top::tvm_engine::parameters::PReturnResult_PLog, address_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::top::tvm_engine::parameters::PReturnResult_PLog, topics_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::top::tvm_engine::parameters::PReturnResult_PLog, data_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::top::tvm_engine::parameters::PReturnResult, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::top::tvm_engine::parameters::PReturnResult, status_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::top::tvm_engine::parameters::PReturnResult, status_data_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::top::tvm_engine::parameters::PReturnResult, gas_used_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::top::tvm_engine::parameters::PReturnResult, logs_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::top::tvm_engine::parameters::PCallArgs, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::top::tvm_engine::parameters::PCallArgs, sender_address_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::top::tvm_engine::parameters::PCallArgs, recver_address_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::top::tvm_engine::parameters::PCallArgs, value_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::top::tvm_engine::parameters::PCallArgs, input_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::top::tvm_engine::parameters::PCallArgs, gas_limit_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::top::tvm_engine::parameters::PReturnResult_PU256)},
  { 6, -1, sizeof(::top::tvm_engine::parameters::PReturnResult_PLog)},
  { 14, -1, sizeof(::top::tvm_engine::parameters::PReturnResult)},
  { 23, -1, sizeof(::top::tvm_engine::parameters::PCallArgs)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::top::tvm_engine::parameters::_PReturnResult_PU256_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::top::tvm_engine::parameters::_PReturnResult_PLog_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::top::tvm_engine::parameters::_PReturnResult_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::top::tvm_engine::parameters::_PCallArgs_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "protobuf_types/pparameters.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n protobuf_types/pparameters.proto\022\031top."
      "tvm_engine.parameters\032\033protobuf_types/pb"
      "asic.proto\"\242\002\n\rPReturnResult\022\016\n\006status\030\001"
      " \001(\r\022\023\n\013status_data\030\002 \001(\014\022\020\n\010gas_used\030\003 "
      "\001(\004\022;\n\004logs\030\004 \003(\0132-.top.tvm_engine.param"
      "eters.PReturnResult.PLog\032\025\n\005PU256\022\014\n\004dat"
      "a\030\001 \001(\014\032\205\001\n\004PLog\022/\n\007address\030\001 \001(\0132\036.top."
      "tvm_engine.basic.PAddress\022>\n\006topics\030\002 \003("
      "\0132..top.tvm_engine.parameters.PReturnRes"
      "ult.PU256\022\014\n\004data\030\003 \001(\014\"\254\001\n\tPCallArgs\0226\n"
      "\016sender_address\030\001 \001(\0132\036.top.tvm_engine.b"
      "asic.PAddress\0226\n\016recver_address\030\002 \001(\0132\036."
      "top.tvm_engine.basic.PAddress\022\r\n\005value\030\003"
      " \001(\004\022\r\n\005input\030\004 \001(\014\022\021\n\tgas_limit\030\005 \001(\004b\006"
      "proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 566);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "protobuf_types/pparameters.proto", &protobuf_RegisterTypes);
  ::protobuf_protobuf_5ftypes_2fpbasic_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_protobuf_5ftypes_2fpparameters_2eproto
namespace top {
namespace tvm_engine {
namespace parameters {

// ===================================================================

void PReturnResult_PU256::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PReturnResult_PU256::kDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PReturnResult_PU256::PReturnResult_PU256()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_protobuf_5ftypes_2fpparameters_2eproto::scc_info_PReturnResult_PU256.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:top.tvm_engine.parameters.PReturnResult.PU256)
}
PReturnResult_PU256::PReturnResult_PU256(const PReturnResult_PU256& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.data().size() > 0) {
    data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.data_);
  }
  // @@protoc_insertion_point(copy_constructor:top.tvm_engine.parameters.PReturnResult.PU256)
}

void PReturnResult_PU256::SharedCtor() {
  data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

PReturnResult_PU256::~PReturnResult_PU256() {
  // @@protoc_insertion_point(destructor:top.tvm_engine.parameters.PReturnResult.PU256)
  SharedDtor();
}

void PReturnResult_PU256::SharedDtor() {
  data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void PReturnResult_PU256::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* PReturnResult_PU256::descriptor() {
  ::protobuf_protobuf_5ftypes_2fpparameters_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_protobuf_5ftypes_2fpparameters_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PReturnResult_PU256& PReturnResult_PU256::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_protobuf_5ftypes_2fpparameters_2eproto::scc_info_PReturnResult_PU256.base);
  return *internal_default_instance();
}


void PReturnResult_PU256::Clear() {
// @@protoc_insertion_point(message_clear_start:top.tvm_engine.parameters.PReturnResult.PU256)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool PReturnResult_PU256::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:top.tvm_engine.parameters.PReturnResult.PU256)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes data = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_data()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:top.tvm_engine.parameters.PReturnResult.PU256)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:top.tvm_engine.parameters.PReturnResult.PU256)
  return false;
#undef DO_
}

void PReturnResult_PU256::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:top.tvm_engine.parameters.PReturnResult.PU256)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes data = 1;
  if (this->data().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->data(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:top.tvm_engine.parameters.PReturnResult.PU256)
}

::google::protobuf::uint8* PReturnResult_PU256::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:top.tvm_engine.parameters.PReturnResult.PU256)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes data = 1;
  if (this->data().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->data(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:top.tvm_engine.parameters.PReturnResult.PU256)
  return target;
}

size_t PReturnResult_PU256::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:top.tvm_engine.parameters.PReturnResult.PU256)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes data = 1;
  if (this->data().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->data());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PReturnResult_PU256::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:top.tvm_engine.parameters.PReturnResult.PU256)
  GOOGLE_DCHECK_NE(&from, this);
  const PReturnResult_PU256* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PReturnResult_PU256>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:top.tvm_engine.parameters.PReturnResult.PU256)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:top.tvm_engine.parameters.PReturnResult.PU256)
    MergeFrom(*source);
  }
}

void PReturnResult_PU256::MergeFrom(const PReturnResult_PU256& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:top.tvm_engine.parameters.PReturnResult.PU256)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.data().size() > 0) {

    data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.data_);
  }
}

void PReturnResult_PU256::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:top.tvm_engine.parameters.PReturnResult.PU256)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PReturnResult_PU256::CopyFrom(const PReturnResult_PU256& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:top.tvm_engine.parameters.PReturnResult.PU256)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PReturnResult_PU256::IsInitialized() const {
  return true;
}

void PReturnResult_PU256::Swap(PReturnResult_PU256* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PReturnResult_PU256::InternalSwap(PReturnResult_PU256* other) {
  using std::swap;
  data_.Swap(&other->data_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata PReturnResult_PU256::GetMetadata() const {
  protobuf_protobuf_5ftypes_2fpparameters_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_protobuf_5ftypes_2fpparameters_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void PReturnResult_PLog::InitAsDefaultInstance() {
  ::top::tvm_engine::parameters::_PReturnResult_PLog_default_instance_._instance.get_mutable()->address_ = const_cast< ::top::tvm_engine::basic::PAddress*>(
      ::top::tvm_engine::basic::PAddress::internal_default_instance());
}
void PReturnResult_PLog::clear_address() {
  if (GetArenaNoVirtual() == NULL && address_ != NULL) {
    delete address_;
  }
  address_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PReturnResult_PLog::kAddressFieldNumber;
const int PReturnResult_PLog::kTopicsFieldNumber;
const int PReturnResult_PLog::kDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PReturnResult_PLog::PReturnResult_PLog()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_protobuf_5ftypes_2fpparameters_2eproto::scc_info_PReturnResult_PLog.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:top.tvm_engine.parameters.PReturnResult.PLog)
}
PReturnResult_PLog::PReturnResult_PLog(const PReturnResult_PLog& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      topics_(from.topics_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.data().size() > 0) {
    data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.data_);
  }
  if (from.has_address()) {
    address_ = new ::top::tvm_engine::basic::PAddress(*from.address_);
  } else {
    address_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:top.tvm_engine.parameters.PReturnResult.PLog)
}

void PReturnResult_PLog::SharedCtor() {
  data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  address_ = NULL;
}

PReturnResult_PLog::~PReturnResult_PLog() {
  // @@protoc_insertion_point(destructor:top.tvm_engine.parameters.PReturnResult.PLog)
  SharedDtor();
}

void PReturnResult_PLog::SharedDtor() {
  data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete address_;
}

void PReturnResult_PLog::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* PReturnResult_PLog::descriptor() {
  ::protobuf_protobuf_5ftypes_2fpparameters_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_protobuf_5ftypes_2fpparameters_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PReturnResult_PLog& PReturnResult_PLog::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_protobuf_5ftypes_2fpparameters_2eproto::scc_info_PReturnResult_PLog.base);
  return *internal_default_instance();
}


void PReturnResult_PLog::Clear() {
// @@protoc_insertion_point(message_clear_start:top.tvm_engine.parameters.PReturnResult.PLog)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  topics_.Clear();
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && address_ != NULL) {
    delete address_;
  }
  address_ = NULL;
  _internal_metadata_.Clear();
}

bool PReturnResult_PLog::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:top.tvm_engine.parameters.PReturnResult.PLog)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .top.tvm_engine.basic.PAddress address = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_address()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .top.tvm_engine.parameters.PReturnResult.PU256 topics = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_topics()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes data = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_data()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:top.tvm_engine.parameters.PReturnResult.PLog)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:top.tvm_engine.parameters.PReturnResult.PLog)
  return false;
#undef DO_
}

void PReturnResult_PLog::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:top.tvm_engine.parameters.PReturnResult.PLog)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .top.tvm_engine.basic.PAddress address = 1;
  if (this->has_address()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_address(), output);
  }

  // repeated .top.tvm_engine.parameters.PReturnResult.PU256 topics = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->topics_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2,
      this->topics(static_cast<int>(i)),
      output);
  }

  // bytes data = 3;
  if (this->data().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      3, this->data(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:top.tvm_engine.parameters.PReturnResult.PLog)
}

::google::protobuf::uint8* PReturnResult_PLog::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:top.tvm_engine.parameters.PReturnResult.PLog)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .top.tvm_engine.basic.PAddress address = 1;
  if (this->has_address()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_address(), deterministic, target);
  }

  // repeated .top.tvm_engine.parameters.PReturnResult.PU256 topics = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->topics_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->topics(static_cast<int>(i)), deterministic, target);
  }

  // bytes data = 3;
  if (this->data().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        3, this->data(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:top.tvm_engine.parameters.PReturnResult.PLog)
  return target;
}

size_t PReturnResult_PLog::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:top.tvm_engine.parameters.PReturnResult.PLog)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .top.tvm_engine.parameters.PReturnResult.PU256 topics = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->topics_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->topics(static_cast<int>(i)));
    }
  }

  // bytes data = 3;
  if (this->data().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->data());
  }

  // .top.tvm_engine.basic.PAddress address = 1;
  if (this->has_address()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *address_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PReturnResult_PLog::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:top.tvm_engine.parameters.PReturnResult.PLog)
  GOOGLE_DCHECK_NE(&from, this);
  const PReturnResult_PLog* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PReturnResult_PLog>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:top.tvm_engine.parameters.PReturnResult.PLog)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:top.tvm_engine.parameters.PReturnResult.PLog)
    MergeFrom(*source);
  }
}

void PReturnResult_PLog::MergeFrom(const PReturnResult_PLog& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:top.tvm_engine.parameters.PReturnResult.PLog)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  topics_.MergeFrom(from.topics_);
  if (from.data().size() > 0) {

    data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.data_);
  }
  if (from.has_address()) {
    mutable_address()->::top::tvm_engine::basic::PAddress::MergeFrom(from.address());
  }
}

void PReturnResult_PLog::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:top.tvm_engine.parameters.PReturnResult.PLog)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PReturnResult_PLog::CopyFrom(const PReturnResult_PLog& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:top.tvm_engine.parameters.PReturnResult.PLog)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PReturnResult_PLog::IsInitialized() const {
  return true;
}

void PReturnResult_PLog::Swap(PReturnResult_PLog* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PReturnResult_PLog::InternalSwap(PReturnResult_PLog* other) {
  using std::swap;
  CastToBase(&topics_)->InternalSwap(CastToBase(&other->topics_));
  data_.Swap(&other->data_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(address_, other->address_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata PReturnResult_PLog::GetMetadata() const {
  protobuf_protobuf_5ftypes_2fpparameters_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_protobuf_5ftypes_2fpparameters_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void PReturnResult::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PReturnResult::kStatusFieldNumber;
const int PReturnResult::kStatusDataFieldNumber;
const int PReturnResult::kGasUsedFieldNumber;
const int PReturnResult::kLogsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PReturnResult::PReturnResult()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_protobuf_5ftypes_2fpparameters_2eproto::scc_info_PReturnResult.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:top.tvm_engine.parameters.PReturnResult)
}
PReturnResult::PReturnResult(const PReturnResult& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      logs_(from.logs_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  status_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.status_data().size() > 0) {
    status_data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.status_data_);
  }
  ::memcpy(&gas_used_, &from.gas_used_,
    static_cast<size_t>(reinterpret_cast<char*>(&status_) -
    reinterpret_cast<char*>(&gas_used_)) + sizeof(status_));
  // @@protoc_insertion_point(copy_constructor:top.tvm_engine.parameters.PReturnResult)
}

void PReturnResult::SharedCtor() {
  status_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&gas_used_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&status_) -
      reinterpret_cast<char*>(&gas_used_)) + sizeof(status_));
}

PReturnResult::~PReturnResult() {
  // @@protoc_insertion_point(destructor:top.tvm_engine.parameters.PReturnResult)
  SharedDtor();
}

void PReturnResult::SharedDtor() {
  status_data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void PReturnResult::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* PReturnResult::descriptor() {
  ::protobuf_protobuf_5ftypes_2fpparameters_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_protobuf_5ftypes_2fpparameters_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PReturnResult& PReturnResult::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_protobuf_5ftypes_2fpparameters_2eproto::scc_info_PReturnResult.base);
  return *internal_default_instance();
}


void PReturnResult::Clear() {
// @@protoc_insertion_point(message_clear_start:top.tvm_engine.parameters.PReturnResult)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  logs_.Clear();
  status_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&gas_used_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&status_) -
      reinterpret_cast<char*>(&gas_used_)) + sizeof(status_));
  _internal_metadata_.Clear();
}

bool PReturnResult::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:top.tvm_engine.parameters.PReturnResult)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 status = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &status_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes status_data = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_status_data()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 gas_used = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &gas_used_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .top.tvm_engine.parameters.PReturnResult.PLog logs = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_logs()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:top.tvm_engine.parameters.PReturnResult)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:top.tvm_engine.parameters.PReturnResult)
  return false;
#undef DO_
}

void PReturnResult::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:top.tvm_engine.parameters.PReturnResult)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 status = 1;
  if (this->status() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->status(), output);
  }

  // bytes status_data = 2;
  if (this->status_data().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->status_data(), output);
  }

  // uint64 gas_used = 3;
  if (this->gas_used() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(3, this->gas_used(), output);
  }

  // repeated .top.tvm_engine.parameters.PReturnResult.PLog logs = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->logs_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4,
      this->logs(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:top.tvm_engine.parameters.PReturnResult)
}

::google::protobuf::uint8* PReturnResult::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:top.tvm_engine.parameters.PReturnResult)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 status = 1;
  if (this->status() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->status(), target);
  }

  // bytes status_data = 2;
  if (this->status_data().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->status_data(), target);
  }

  // uint64 gas_used = 3;
  if (this->gas_used() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(3, this->gas_used(), target);
  }

  // repeated .top.tvm_engine.parameters.PReturnResult.PLog logs = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->logs_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, this->logs(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:top.tvm_engine.parameters.PReturnResult)
  return target;
}

size_t PReturnResult::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:top.tvm_engine.parameters.PReturnResult)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .top.tvm_engine.parameters.PReturnResult.PLog logs = 4;
  {
    unsigned int count = static_cast<unsigned int>(this->logs_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->logs(static_cast<int>(i)));
    }
  }

  // bytes status_data = 2;
  if (this->status_data().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->status_data());
  }

  // uint64 gas_used = 3;
  if (this->gas_used() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->gas_used());
  }

  // uint32 status = 1;
  if (this->status() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->status());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PReturnResult::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:top.tvm_engine.parameters.PReturnResult)
  GOOGLE_DCHECK_NE(&from, this);
  const PReturnResult* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PReturnResult>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:top.tvm_engine.parameters.PReturnResult)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:top.tvm_engine.parameters.PReturnResult)
    MergeFrom(*source);
  }
}

void PReturnResult::MergeFrom(const PReturnResult& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:top.tvm_engine.parameters.PReturnResult)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  logs_.MergeFrom(from.logs_);
  if (from.status_data().size() > 0) {

    status_data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.status_data_);
  }
  if (from.gas_used() != 0) {
    set_gas_used(from.gas_used());
  }
  if (from.status() != 0) {
    set_status(from.status());
  }
}

void PReturnResult::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:top.tvm_engine.parameters.PReturnResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PReturnResult::CopyFrom(const PReturnResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:top.tvm_engine.parameters.PReturnResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PReturnResult::IsInitialized() const {
  return true;
}

void PReturnResult::Swap(PReturnResult* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PReturnResult::InternalSwap(PReturnResult* other) {
  using std::swap;
  CastToBase(&logs_)->InternalSwap(CastToBase(&other->logs_));
  status_data_.Swap(&other->status_data_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(gas_used_, other->gas_used_);
  swap(status_, other->status_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata PReturnResult::GetMetadata() const {
  protobuf_protobuf_5ftypes_2fpparameters_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_protobuf_5ftypes_2fpparameters_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void PCallArgs::InitAsDefaultInstance() {
  ::top::tvm_engine::parameters::_PCallArgs_default_instance_._instance.get_mutable()->sender_address_ = const_cast< ::top::tvm_engine::basic::PAddress*>(
      ::top::tvm_engine::basic::PAddress::internal_default_instance());
  ::top::tvm_engine::parameters::_PCallArgs_default_instance_._instance.get_mutable()->recver_address_ = const_cast< ::top::tvm_engine::basic::PAddress*>(
      ::top::tvm_engine::basic::PAddress::internal_default_instance());
}
void PCallArgs::clear_sender_address() {
  if (GetArenaNoVirtual() == NULL && sender_address_ != NULL) {
    delete sender_address_;
  }
  sender_address_ = NULL;
}
void PCallArgs::clear_recver_address() {
  if (GetArenaNoVirtual() == NULL && recver_address_ != NULL) {
    delete recver_address_;
  }
  recver_address_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PCallArgs::kSenderAddressFieldNumber;
const int PCallArgs::kRecverAddressFieldNumber;
const int PCallArgs::kValueFieldNumber;
const int PCallArgs::kInputFieldNumber;
const int PCallArgs::kGasLimitFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PCallArgs::PCallArgs()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_protobuf_5ftypes_2fpparameters_2eproto::scc_info_PCallArgs.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:top.tvm_engine.parameters.PCallArgs)
}
PCallArgs::PCallArgs(const PCallArgs& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  input_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.input().size() > 0) {
    input_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.input_);
  }
  if (from.has_sender_address()) {
    sender_address_ = new ::top::tvm_engine::basic::PAddress(*from.sender_address_);
  } else {
    sender_address_ = NULL;
  }
  if (from.has_recver_address()) {
    recver_address_ = new ::top::tvm_engine::basic::PAddress(*from.recver_address_);
  } else {
    recver_address_ = NULL;
  }
  ::memcpy(&value_, &from.value_,
    static_cast<size_t>(reinterpret_cast<char*>(&gas_limit_) -
    reinterpret_cast<char*>(&value_)) + sizeof(gas_limit_));
  // @@protoc_insertion_point(copy_constructor:top.tvm_engine.parameters.PCallArgs)
}

void PCallArgs::SharedCtor() {
  input_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&sender_address_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&gas_limit_) -
      reinterpret_cast<char*>(&sender_address_)) + sizeof(gas_limit_));
}

PCallArgs::~PCallArgs() {
  // @@protoc_insertion_point(destructor:top.tvm_engine.parameters.PCallArgs)
  SharedDtor();
}

void PCallArgs::SharedDtor() {
  input_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete sender_address_;
  if (this != internal_default_instance()) delete recver_address_;
}

void PCallArgs::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* PCallArgs::descriptor() {
  ::protobuf_protobuf_5ftypes_2fpparameters_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_protobuf_5ftypes_2fpparameters_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PCallArgs& PCallArgs::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_protobuf_5ftypes_2fpparameters_2eproto::scc_info_PCallArgs.base);
  return *internal_default_instance();
}


void PCallArgs::Clear() {
// @@protoc_insertion_point(message_clear_start:top.tvm_engine.parameters.PCallArgs)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  input_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && sender_address_ != NULL) {
    delete sender_address_;
  }
  sender_address_ = NULL;
  if (GetArenaNoVirtual() == NULL && recver_address_ != NULL) {
    delete recver_address_;
  }
  recver_address_ = NULL;
  ::memset(&value_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&gas_limit_) -
      reinterpret_cast<char*>(&value_)) + sizeof(gas_limit_));
  _internal_metadata_.Clear();
}

bool PCallArgs::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:top.tvm_engine.parameters.PCallArgs)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .top.tvm_engine.basic.PAddress sender_address = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_sender_address()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .top.tvm_engine.basic.PAddress recver_address = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_recver_address()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 value = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &value_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes input = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_input()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 gas_limit = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &gas_limit_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:top.tvm_engine.parameters.PCallArgs)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:top.tvm_engine.parameters.PCallArgs)
  return false;
#undef DO_
}

void PCallArgs::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:top.tvm_engine.parameters.PCallArgs)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .top.tvm_engine.basic.PAddress sender_address = 1;
  if (this->has_sender_address()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_sender_address(), output);
  }

  // .top.tvm_engine.basic.PAddress recver_address = 2;
  if (this->has_recver_address()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_recver_address(), output);
  }

  // uint64 value = 3;
  if (this->value() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(3, this->value(), output);
  }

  // bytes input = 4;
  if (this->input().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      4, this->input(), output);
  }

  // uint64 gas_limit = 5;
  if (this->gas_limit() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(5, this->gas_limit(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:top.tvm_engine.parameters.PCallArgs)
}

::google::protobuf::uint8* PCallArgs::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:top.tvm_engine.parameters.PCallArgs)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .top.tvm_engine.basic.PAddress sender_address = 1;
  if (this->has_sender_address()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_sender_address(), deterministic, target);
  }

  // .top.tvm_engine.basic.PAddress recver_address = 2;
  if (this->has_recver_address()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_recver_address(), deterministic, target);
  }

  // uint64 value = 3;
  if (this->value() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(3, this->value(), target);
  }

  // bytes input = 4;
  if (this->input().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        4, this->input(), target);
  }

  // uint64 gas_limit = 5;
  if (this->gas_limit() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(5, this->gas_limit(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:top.tvm_engine.parameters.PCallArgs)
  return target;
}

size_t PCallArgs::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:top.tvm_engine.parameters.PCallArgs)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes input = 4;
  if (this->input().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->input());
  }

  // .top.tvm_engine.basic.PAddress sender_address = 1;
  if (this->has_sender_address()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *sender_address_);
  }

  // .top.tvm_engine.basic.PAddress recver_address = 2;
  if (this->has_recver_address()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *recver_address_);
  }

  // uint64 value = 3;
  if (this->value() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->value());
  }

  // uint64 gas_limit = 5;
  if (this->gas_limit() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->gas_limit());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PCallArgs::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:top.tvm_engine.parameters.PCallArgs)
  GOOGLE_DCHECK_NE(&from, this);
  const PCallArgs* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PCallArgs>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:top.tvm_engine.parameters.PCallArgs)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:top.tvm_engine.parameters.PCallArgs)
    MergeFrom(*source);
  }
}

void PCallArgs::MergeFrom(const PCallArgs& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:top.tvm_engine.parameters.PCallArgs)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.input().size() > 0) {

    input_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.input_);
  }
  if (from.has_sender_address()) {
    mutable_sender_address()->::top::tvm_engine::basic::PAddress::MergeFrom(from.sender_address());
  }
  if (from.has_recver_address()) {
    mutable_recver_address()->::top::tvm_engine::basic::PAddress::MergeFrom(from.recver_address());
  }
  if (from.value() != 0) {
    set_value(from.value());
  }
  if (from.gas_limit() != 0) {
    set_gas_limit(from.gas_limit());
  }
}

void PCallArgs::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:top.tvm_engine.parameters.PCallArgs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PCallArgs::CopyFrom(const PCallArgs& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:top.tvm_engine.parameters.PCallArgs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PCallArgs::IsInitialized() const {
  return true;
}

void PCallArgs::Swap(PCallArgs* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PCallArgs::InternalSwap(PCallArgs* other) {
  using std::swap;
  input_.Swap(&other->input_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(sender_address_, other->sender_address_);
  swap(recver_address_, other->recver_address_);
  swap(value_, other->value_);
  swap(gas_limit_, other->gas_limit_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata PCallArgs::GetMetadata() const {
  protobuf_protobuf_5ftypes_2fpparameters_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_protobuf_5ftypes_2fpparameters_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace parameters
}  // namespace tvm_engine
}  // namespace top
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::top::tvm_engine::parameters::PReturnResult_PU256* Arena::CreateMaybeMessage< ::top::tvm_engine::parameters::PReturnResult_PU256 >(Arena* arena) {
  return Arena::CreateInternal< ::top::tvm_engine::parameters::PReturnResult_PU256 >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::top::tvm_engine::parameters::PReturnResult_PLog* Arena::CreateMaybeMessage< ::top::tvm_engine::parameters::PReturnResult_PLog >(Arena* arena) {
  return Arena::CreateInternal< ::top::tvm_engine::parameters::PReturnResult_PLog >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::top::tvm_engine::parameters::PReturnResult* Arena::CreateMaybeMessage< ::top::tvm_engine::parameters::PReturnResult >(Arena* arena) {
  return Arena::CreateInternal< ::top::tvm_engine::parameters::PReturnResult >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::top::tvm_engine::parameters::PCallArgs* Arena::CreateMaybeMessage< ::top::tvm_engine::parameters::PCallArgs >(Arena* arena) {
  return Arena::CreateInternal< ::top::tvm_engine::parameters::PCallArgs >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
